#!/usr/bin/env node
/**
 * Regenerate the success chance of every (advantage state, threshold) pair in
 * the Tno dice mechanic, into two artifacts:
 *
 * - `module/helpers/dice-odds-table.mjs` — the shipped lookup table the roll
 *   dialog and chat card read at runtime.
 * - `docs/design/dice-odds.md` — the human-readable tables.
 *
 * The outcome space is tiny — 8,000 hands for 3d20, 400 for 2d20 — so the
 * numbers are produced by exhaustive enumeration, not sampling: they are
 * exact. That enumeration happens *here*, once, rather than in the browser:
 * the odds only change when the mechanic changes, so there is nothing for the
 * client to recompute. A Monte Carlo pass (`SAMPLES` rolls per state) runs
 * alongside it purely as a sanity check that the enumeration walks the same
 * space the real dice do; its deviation is reported and expected to stay inside
 * the binomial noise band.
 *
 * Both passes import `dieCountFor` / `pickCountingDie` / `criticalResultFor`
 * straight from `module/helpers/dice.mjs`, so the published odds cannot drift
 * away from the shipped rules — change the mechanic and re-run this to see the
 * new numbers. (Those three helpers are pure; only `rollTno` below them touches
 * Foundry globals, and importing the module does not call it.)
 * `tests/helpers/dice-odds.test.js` re-derives the table the same way and fails
 * if the committed one no longer matches, so a mechanic change cannot ship with
 * a stale table.
 *
 * Usage: npm run docs:odds
 */

import { writeFileSync } from 'node:fs';
import {
  TNO_ADVANTAGE,
  dieCountFor,
  pickCountingDie,
  criticalResultFor,
} from '../module/helpers/dice.mjs';

/** Advantage states in display order, best to worst. */
const STATES = [
  { key: 'strongAdvantage', label: 'Strong Adv' },
  { key: 'advantage', label: 'Advantage' },
  { key: 'none', label: 'None' },
  { key: 'disadvantage', label: 'Disadv.' },
  { key: 'strongDisadvantage', label: 'Strong Dis' },
];

const SAMPLES = 10000000;
const OUT = 'docs/design/dice-odds.md';
const OUT_TABLE = 'module/helpers/dice-odds-table.mjs';

/** Probabilities are emitted at this precision — far past any display need. */
const round = (x) => Number(x.toFixed(8));

/** Every possible result of `n` d20, in order. */
function* allRolls(n) {
  if (n === 2) {
    for (let a = 1; a <= 20; a++) for (let b = 1; b <= 20; b++) yield [a, b];
    return;
  }
  for (let a = 1; a <= 20; a++) for (let b = 1; b <= 20; b++) for (let c = 1; c <= 20; c++) yield [a, b, c];
}

/**
 * Score one rolled hand into the tally: a critical short-circuits every
 * threshold at once (it ignores the threshold), otherwise the counting die
 * succeeds against every threshold at or above it.
 */
function tally(values, advantage, acc) {
  const critical = criticalResultFor(values, advantage);
  if (critical === 'criticalSuccess') {
    acc.crit++;
    for (let th = 0; th <= 20; th++) acc.success[th]++;
    return;
  }
  if (critical === 'criticalFailure') {
    acc.fumble++;
    return;
  }
  const { value } = pickCountingDie(values, advantage);
  for (let th = value; th <= 20; th++) {
    acc.success[th]++;
    acc.plain[th]++;
  }
}

const emptyAcc = () => ({ crit: 0, fumble: 0, success: new Array(21).fill(0), plain: new Array(21).fill(0) });
const d20 = () => 1 + Math.floor(Math.random() * 20);

const exact = {};
const sim = {};

for (const { key } of STATES) {
  const advantage = TNO_ADVANTAGE[key];
  const dice = dieCountFor(advantage);

  const e = emptyAcc();
  let total = 0;
  for (const values of allRolls(dice)) {
    tally(values, advantage, e);
    total++;
  }
  exact[key] = {
    dice,
    crit: e.crit / total,
    fumble: e.fumble / total,
    success: e.success.map((n) => n / total),
    plain: e.plain.map((n) => n / total),
  };

  const s = emptyAcc();
  for (let i = 0; i < SAMPLES; i++) tally(Array.from({ length: dice }, d20), advantage, s);
  sim[key] = {
    crit: s.crit / SAMPLES,
    fumble: s.fumble / SAMPLES,
    success: s.success.map((n) => n / SAMPLES),
  };
}

const pct = (x) => (x * 100).toFixed(2);
const signed = (x) => (x >= 0 ? '+' : '') + x.toFixed(2);

const cells = STATES.length * 21;
let maxDelta = 0;
for (const { key } of STATES) {
  for (let th = 0; th <= 20; th++) {
    maxDelta = Math.max(maxDelta, Math.abs(sim[key].success[th] - exact[key].success[th]) * 100);
  }
}
// Widest 95% interval a fair sample of this size can produce (p = 0.5).
const band = 1.96 * Math.sqrt(0.25 / SAMPLES) * 100;

const row = (head, cells) => `| ${head} | ${cells.join(' | ')} |`;
const header = (head) => [row(head, STATES.map((s) => s.label)), row('---:', STATES.map(() => '---:'))];

const md = [
  '# Dice odds',
  '',
  'Generated by `npm run docs:odds` — do not edit by hand.',
  '',
  'Success chance of every threshold under every advantage state, for the 3d20',
  'roll-under mechanic specified in [`dice-system-prd.md`](dice-system-prd.md)',
  'and implemented in [`module/helpers/dice.mjs`](../../module/helpers/dice.mjs).',
  '',
  'The numbers are **exact**, not sampled: the generator enumerates the whole',
  'outcome space (8,000 hands for 3d20, 400 for 2d20) using the shipped',
  'resolution helpers.',
  '',
  '## Crit and fumble rates',
  '',
  'Independent of the threshold — a critical ignores it entirely.',
  '',
  ...header('Rate'),
  row('Dice', STATES.map((s) => `${exact[s.key].dice}d20`)),
  row('Critical success', STATES.map((s) => `${pct(exact[s.key].crit)}%`)),
  row('Critical fumble', STATES.map((s) => `${pct(exact[s.key].fumble)}%`)),
  '',
  '## Total success chance by threshold',
  '',
  'Critical success counts as a success, fumble as a failure — this is the',
  'chance the roll comes out in the player\'s favour, which is what the GM',
  'actually cares about when setting difficulty.',
  '',
  ...header('Threshold'),
  ...Array.from({ length: 21 }, (_, th) => row(String(th), STATES.map((s) => `${pct(exact[s.key].success[th])}%`))),
  '',
  '## Plain success chance by threshold',
  '',
  'The same table with criticals excluded — the chance of passing on the',
  'counting die alone. The gap against the table above is the crit rate.',
  '',
  ...header('Threshold'),
  ...Array.from({ length: 21 }, (_, th) => row(String(th), STATES.map((s) => `${pct(exact[s.key].plain[th])}%`))),
  '',
  '## Reading the tables',
  '',
  '- **Threshold 0 and 1 are identical, as are 19 and 20.** A counting die of 1',
  '  already triggers a critical success in every state, and a 20 is never a',
  '  plain success in any state, so those two thresholds buy nothing. A maxed',
  '  threshold is not auto-success.',
  '- **Strong Disadvantage caps at ' + pct(exact.strongDisadvantage.success[20]) + '%** no matter how easy the task,',
  '  because its ' + pct(exact.strongDisadvantage.fumble) + '% fumble floor cannot be removed. Symmetrically,',
  '  Strong Advantage never drops below ' + pct(exact.strongAdvantage.success[0]) + '%.',
  '- **Advantage state outweighs any modifier the GM can hand out.** Around the',
  '  middle of the range one step of advantage is worth roughly ±8 points of',
  '  threshold, more than the ±6 a double bonus/malus provides.',
  '- **A ±3 modifier is not worth the same everywhere.** At threshold 10 it buys',
  '  about 15 points of success chance with no advantage, but only ~11 under',
  '  Strong Advantage and ~2 out at threshold 18.',
  '',
  '## Monte Carlo cross-check',
  '',
  `A ${SAMPLES.toLocaleString('en-US')}-roll simulation per state, scored through the same helpers,`,
  'agrees with the enumeration:',
  '',
  ...header('Simulated'),
  row('Critical success', STATES.map((s) => `${pct(sim[s.key].crit)}%`)),
  row('Critical fumble', STATES.map((s) => `${pct(sim[s.key].fumble)}%`)),
  row('At threshold 10', STATES.map((s) => `${pct(sim[s.key].success[10])}%`)),
  row('At threshold 14', STATES.map((s) => `${pct(sim[s.key].success[14])}%`)),
  '',
  `Largest deviation across all ${cells} threshold cells: **${maxDelta.toFixed(2)} pp**, against a`,
  `±${band.toFixed(2)} pp 95% band for a single cell at this sample size. The *largest* of`,
  `${cells} cells is expected to sit somewhat past a per-cell band — the run is`,
  'consistent as long as it stays in the same order of magnitude, and a',
  'deviation of several pp would mean the enumeration and the dice disagree.',
  '',
  'The simulation is re-rolled on every regeneration, so these four rows and the',
  'deviation shift between runs while the exact tables above never move.',
  '',
].join('\n');

// The shipped lookup table. Only what the UI reads: the total success chance
// per threshold plus the two critical rates. The plain-success column exists
// only in the doc above, where it explains the gap between the two tables.
const table = [
  '/**',
  ' * GENERATED by `npm run docs:odds` — do not edit by hand.',
  ' *',
  ' * Exact success probability of the Tno dice mechanic for every advantage',
  ' * state and every threshold 0–20, produced by enumerating the entire outcome',
  ' * space through the resolution helpers in `dice.mjs`. Baked at build time',
  ' * because it is a constant: nothing about it varies per actor, per roll, or',
  ' * per world, so the client has nothing to compute.',
  ' *',
  ' * `success` is indexed by threshold and counts a critical success as a',
  ' * success and a fumble as a failure — the chance the roll goes the player\'s',
  ' * way. `crit` and `fumble` are threshold-independent, since a critical',
  ' * ignores the threshold entirely.',
  ' *',
  ' * Each entry carries its own `key` (the TNO_ADVANTAGE name) and `dice`',
  ' * count so the read side can label a state without importing `dice.mjs` —',
  ' * `dice.mjs` is a leaf module that imports nothing, and it consumes the odds',
  ' * itself when it renders a roll card, so the dependency has to run this way.',
  ' *',
  ' * Read through `successChanceFor()` in `dice-odds.mjs` rather than indexed',
  ' * directly. Guarded by `tests/helpers/dice-odds.test.js`, which re-derives',
  ' * these numbers from the live helpers and fails if they have drifted.',
  ' *',
  ' * @type {Object<string, {key: string, dice: number, crit: number, fumble: number, success: number[]}>}',
  ' */',
  'export const TNO_ODDS = {',
  ...STATES.slice().reverse().flatMap(({ key }) => {
    const advantage = TNO_ADVANTAGE[key];
    const e = exact[key];
    return [
      `  // ${key} (${e.dice}d20)`,
      // Quoted: `-2:` is not a legal object-literal key. Lookup by the numeric
      // TNO_ADVANTAGE value still works — JS coerces the index to a string.
      `  '${advantage}': {`,
      `    key: '${key}',`,
      `    dice: ${e.dice},`,
      `    crit: ${round(e.crit)},`,
      `    fumble: ${round(e.fumble)},`,
      '    success: [',
      // Seven per line, so the 21 thresholds land as three tidy rows.
      ...[0, 7, 14].map((start) => `      ${e.success.slice(start, start + 7).map(round).join(', ')},`),
      '    ],',
      '  },',
    ];
  }),
  '};',
  '',
].join('\n');

writeFileSync(OUT_TABLE, table);
writeFileSync(OUT, md);
console.log(`${OUT_TABLE} written`);
console.log(`${OUT} written — max Monte Carlo deviation ${maxDelta.toFixed(2)} pp (95% band ±${band.toFixed(2)} pp)`);
